AllCops:
  Exclude:
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/**/*'

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 40
